#!/usr/bin/env bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging
set -eu +x -o pipefail

payload=$TMPDIR/cf-tracker-resource-request
cat > "$payload" <&0

PROJECT_ID=$(jq -r '.source.project_id' < "$payload")
LABEL=$(jq -r '.source.label' < "$payload")

# get list of all story ids in project with Security Triage label
STORY_LIST=$(wget --quiet --no-verbose -O - "https://www.pivotaltracker.com/services/v5/projects/${PROJECT_ID}/search?query=label%3A${LABEL}%20AND%20state%3Aunscheduled" | jq -r ".stories.stories|sort_by(.created_at)|reverse|map({ ref: .id|tostring, description })")

# shellcheck disable=SC2086
echo $STORY_LIST | jq -R '.' | jq -s "map({ ref: . })" >&3

