#!/usr/bin/env bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging
set -eu +x -o pipefail

SOURCEDIR=$1
payload=$TMPDIR/cf-tracker-resource-put
cat > "$payload" <&0

FILE=$(jq -r '.params.file' < "$payload")

cat "$SOURCEDIR/$FILE"

jq -r '{version:{ref: .version.ref}}' < "$payload" >&3
