#!/usr/bin/env ruby
# encoding: utf-8

require 'fileutils'
require 'yaml'
require_relative 'common'

Dir.chdir 'cf-release' do
  system %(bundle && bosh --parallel 10 sync blobs)
end

release_names.each do |language|
  FileUtils.mkdir_p File.join('cf-release', 'blobs', "#{language}-buildpack")
  blobs = YAML.load File.read('cf-release/config/blobs.yml')
  key = find_buildpack_key blobs, language
  src = Dir["#{language}-buildpack-github-release/*.zip"].first
  next unless src
  dst = "cf-release/blobs/#{key}"
  FileUtils.mv src, dst
end

Dir.chdir 'cf-release' do
  system %(bosh create release --force --with-tarball --name cf --version 212.0.#{Time.now.to_i})
end

system('rsync -a cf-release/ cf-release-artifacts')
