#!/usr/bin/env ruby
# encoding: utf-8

$stdout.sync = true

require 'yaml'
require 'fileutils'
require 'digest/sha1'

release_names = Dir['*-buildpack-github-release'].collect { |name| name.split('-')[0] }

Dir.chdir('cf-release')
blob_store_private_yml = {
  'blobstore' => {
    's3' => {
      'access_key_id' => ENV['ACCESS_KEY_ID'],
      'secret_access_key' => ENV['SECRET_ACCESS_KEY']
    }
  }
}.to_yaml

File.write('config/private.yml', blob_store_private_yml)

release_names.each do |language|
  buildpack_blob = Dir["../#{language}-buildpack-github-release/#{language}_buildpack-cached-*.zip"].first

  system "rm -f blobs/#{language}-buildpack/*"
  blobs = YAML.load(File.read('config/blobs.yml'))

  old_buildpack_key = blobs.keys.detect do |key|
    key =~ /^#{language}-buildpack\//
  end

  next unless old_buildpack_key
  new_sha = Digest::SHA1.file(buildpack_blob).hexdigest

  next unless new_sha != blobs[old_buildpack_key]['sha']
  blobs.delete(old_buildpack_key)
  File.write('config/blobs.yml', YAML.dump(blobs))
  exit 1 unless system "bosh add blob #{buildpack_blob} #{language}-buildpack"
end

exit system(<<-EOF)
  set -ex

  bosh -n upload blobs
  /usr/bin/env bash ./scripts/setup-git-hooks

  ref=$(cd ../buildpack-releases && git rev-parse HEAD)
  cd src/buildpacks
  git fetch
  git checkout $ref
  cd ../..
  git add -A
  git commit -am "bump $BUILDPACK_NAME"
EOF
