#!/usr/bin/env ruby
# encoding: utf-8

$stdout.sync = true

require 'yaml'
require 'fileutils'
require 'digest/sha1'

release_names = `ls | grep buildpack-github-release | cut -d '-' -f 1`.chomp.split

Dir.chdir('cf-release')
blob_store_private_yml = %(
---
blobstore:
  s3:
    access_key_id: #{ENV['ACCESS_KEY_ID']}
    secret_access_key: #{ENV['SECRET_ACCESS_KEY']}
)

File.write('config/private.yml', blob_store_private_yml)

release_names.each do |language|
  buildpack_blob     = Dir["../#{language}-buildpack-github-release/#{language}_buildpack-cached-*.zip"].first
  buildpack_path     = "#{language}-buildpack/#{File.basename(buildpack_blob)}"

  system "rm -f blobs/#{language}-buildpack/*"
  blobs = YAML.load(File.read('config/blobs.yml'))

  old_buildpack_key = blobs.keys.detect do |key|
    key =~ /^#{language}-buildpack\//
  end

  next unless old_buildpack_key
  new_sha = Digest::SHA1.file(buildpack_blob).hexdigest

  next unless new_sha != blobs[old_buildpack_key]['sha']
  blobs.delete(old_buildpack_key)
  File.write('config/blobs.yml', YAML.dump(blobs))
  exit 1 unless system "bosh add blob #{buildpack_blob} #{language}-buildpack"
end

exit system(<<-EOF)
  set -e

  bosh -n upload blobs
  git add -A
  git config --global user.email "cf-buildpacks-eng@pivotal.io"
  git config --global user.name "CF Buildpacks Team"

  /usr/bin/env bash ./scripts/setup-git-hooks
  git commit -m 'Upgrading buildpacks to latest versions'
EOF
