#!/bin/bash -l

latest_shasum=$(ls buildpack-artifacts/*.SHA256SUM.txt)
rsync -a buildpack-checksums/ sha-artifacts
cp $latest_shasum ./sha-artifacts
cd sha-artifacts
git add -A
git commit -m "SHA256SUM for $(basename $latest_shasum .SHA256SUM.txt)"
