#!/usr/bin/env bash

latest_shasum=$(ls finalize-buildpack/pivotal-buildpacks-cached/*.SHA256SUM.txt)
cp $latest_shasum ./buildpack-checksums
cd buildpack-checksums
git add -A
git commit -m "SHA256SUM for $(basename $latest_shasum .SHA256SUM.txt)"
