#!/bin/bash
set -euo pipefail

if [ $(cat CHANGELOG | grep -c ^v[0-9]) -ge 2 ]; then
  csplit -s -f CHANGES_ CHANGELOG /^v[0-9]/ /^v[0-9]/
  sed "1,3d" CHANGES_01 > RECENT_CHANGES
  rm CHANGES_*
else
  sed "1,3d" CHANGELOG > RECENT_CHANGES
fi
