#!/usr/bin/env ruby
require 'digest'
require 'fileutils'

Dir.chdir('pivotal-buildpacks-cached') do
  Dir.glob("*.zip").map do |filename|
    filename.match(/(.*)_buildpack-cached-v(.*)\+.*.zip/) do |match|
      _, language, version = match.to_a
      new_filename = "#{language}_buildpack-cached-v#{version}.zip"
      sha_filename = "#{new_filename}.SHA256SUM.txt"

      FileUtils.mv(filename, new_filename)

      shasum = Digest::SHA256.file(new_filename).hexdigest
      File.write(sha_filename, "#{shasum}  #{new_filename}")

      # append SHA to RELEASE NOTES
      File.write('../buildpack/RECENT_CHANGES', "  * SHA256: #{shasum}",mode: 'a')
    end
  end
end
