#!/bin/bash
set -euo pipefail

function __check_usage {
  if [ ${number_of_arguments} -ne 1 ] || ([ ${action} != "add" ] && [ ${action} != "remove" ]); then
    echo "Usage:"
    echo "  $0 [add|remove]"
    exit 1
  fi
}

function __parse_arguments {
  number_of_arguments=$#
  action=${1:-''}
}

function __remove {
  git config --local --remove-section credential
  echo "Jenkins Git credentials removed"
}

function __add {
  echo "https://${GITHUB_CREDENTIALS}@github.com" > $TMPDIR/git.cred
  git config credential.helper 'store --file=$TMPDIR/git.cred'
  echo "Jenkins Git credentials installed"
}

__parse_arguments $@
__check_usage
__$action
