#!/bin/bash
set -euo pipefail

tag=v`cat buildpack/VERSION`
echo -n $tag > tag
pushd buildpack
../buildpacks-ci/scripts/release/extract-recent-changes
BUNDLE_GEMFILE=cf.Gemfile bundle -j4
echo 'Packaged binaries:' >> RECENT_CHANGES
echo >> RECENT_CHANGES
BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --list >> RECENT_CHANGES
popd
