#!/bin/bash -l
set -e

DEPLOYMENT_NAME=`cat cf-environments/name`

pushd deployments-buildpacks
  bundle -j4
  source ./bin/switch $DEPLOYMENT_NAME
popd

cp pivotal-buildpacks/*.zip buildpack
cp pivotal-buildpacks-cached/*.zip buildpack
cd buildpack

export BUNDLE_GEMFILE=cf.Gemfile
bundle -j4 --no-cache

for stack in $STACKS; do
  bundle exec buildpack-build --uncached --stack=$stack --host=$DEPLOYMENT_NAME.cf-app.com --no-build
  bundle exec buildpack-build --cached --stack=$stack --host=$DEPLOYMENT_NAME.cf-app.com --no-build
done
