#!/bin/bash
set -euo pipefail

pushd ci-tools
bundle -j4
popd

pushd buildpack
../buildpacks-ci/scripts/release/extract-recent-changes
popd

./buildpacks-ci/scripts/release/finalize-buildpack

ci-tools/upload_to_pivnet \
  "$PIVNET_PRODUCT_NAME" \
  `cat buildpack/VERSION` \
  pivotal-buildpacks-cached/*_buildpack-cached-v*.zip \
  buildpack/RECENT_CHANGES < /dev/null
