#!/bin/bash
set -euo pipefail

pushd ci-tools
bundle -j4
popd

pushd buildpack
../ci-tools/extract-recent-changes
popd

pushd pivotal-buildpacks-cached
ruby <<RUBY
require "fileutils"
Dir.glob("*.zip").map do |filename|
  filename.match(/(.*)_buildpack-cached-v(.*)\+.*.zip/) do |match|
    language = match[1]
    version = match[2]
    FileUtils.mv(filename, "#{language}_buildpack-cached-v#{version}.zip")
  end
end
RUBY
popd

ci-tools/upload_to_pivnet \
  "$PIVNET_PRODUCT_NAME" \
  `cat buildpack/VERSION` \
  pivotal-buildpacks-cached/*_buildpack-cached-v*.zip \
  buildpack/RECENT_CHANGES < /dev/null
