---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: cfbuildpacks/ci
    username: ((coredeps-dockerhub-user.username))
    password: ((coredeps-dockerhub-user.password))
inputs:
  - name: stack-s3
outputs:
  - name: docker-s3
run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    mv stack-s3/$STACK-*.tar.gz docker-s3/$STACK.tar.gz
    cat > docker-s3/Dockerfile <<EOF
    FROM scratch
    ADD $STACK.tar.gz /
    EOF
params:
  STACK:
