#!/bin/bash -l
set -ex

pushd buildpacks-ci
  bundle install
popd

pushd buildpack-packager
  bump patch
  bump current | egrep -o '[0-9\.]+' >> VERSION
popd

rsync -a buildpack-packager/ buildpack-packager-artifacts
