resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: {{buildpacks-ci-git-uri-public}}
      branch: {{buildpacks-ci-git-uri-public-develop-branch}}
      paths: [ "Dockerfile", "build/*", "Gemfile"]
  - name: buildpacks-ci-image
    type: docker-image
    source:
      repository: {{buildpacks-docker-ci-repo}}
      email: {{buildpacks-docker-user-email}}
      username: {{buildpacks-docker-user-username}}
      password: {{buildpacks-docker-user-password}}
  - name: failure-alert
    type: slack-notification
    source:
      url: {{concourse-job-failure-notifications-slack-webhook}}
jobs:
  - name: ci-build
    serial: true
    public: true
    plan:
      - get: buildpacks-ci
        trigger: true
      - put: buildpacks-ci-image
        params:
          build: buildpacks-ci
          push: true
        attempts: 5
        on_failure:
          put: failure-alert
          params:
            text: "$BUILD_PIPELINE_NAME $BUILD_JOB_NAME job on Concourse failed! \n Check: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
            channel: {{concourse-job-failure-notifications-slack-channel}}
            username: concourse
            icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
