resources:
  - name: buildpacks-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/buildpacks-ci
      branch: develop
  - name: buildpacks-ci-image
    type: docker-image
    source:
      repository: cfbuildpacks/ci
      email: cf-buildpacks-eng@pivotal.io
      username: {{buildpacks-docker-username}}
      password: {{buildpacks-docker-password}}

jobs:
  - name: ci-build
    serial: true
    plan:
      - get: buildpacks-ci
        trigger: true
      - put: buildpacks-ci-image
        params:
          build: buildpacks-ci
          push: true
