#!/usr/bin/env ruby
# encoding: utf-8

buildpacks_ci_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))
new_releases_dir = File.expand_path(File.join(buildpacks_ci_dir, '..', 'new-releases'))

require "#{buildpacks_ci_dir}/lib/slack-client"
require "#{buildpacks_ci_dir}/lib/tracker-client"

Dir.chdir("#{buildpacks_ci_dir}/scripts/notifications") do
  new_releases_output = `./new-releases #{new_releases_dir}`

  unless new_releases_output.nil? || new_releases_output.empty?

    slack_client = SlackClient.new(
      ENV['SLACK_WEBHOOK'],
      ENV['SLACK_CHANNEL'],
      'dependency-notifier'
    )
    slack_client.post_to_slack new_releases_output

    tracker_client = TrackerClient.new(
      ENV['TRACKER_API_TOKEN'],
      ENV['TRACKER_PROJECT_ID'],
      ENV['TRACKER_REQUESTER_ID'].to_i
    )
    tracker_client.post_to_tracker 'Build and/or Include new releases', "We have new releases:\n #{new_releases_output}\n See the google doc https://sites.google.com/a/pivotal.io/cloudfoundry-buildpacks/check-lists/adding-a-new-dependency-release-to-a-buildpack for info on building a new release binary and adding it to the buildpack manifest file."

    Dir.chdir(new_releases_dir) do
      raise 'command failed' unless system('git add -A')
      raise 'command failed' unless system("git commit -m 'Updates for latest tags'")
    end
  end
end
