#!/usr/bin/env ruby
# encoding: utf-8

buildpacks_ci_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))

require "#{buildpacks_ci_dir}/lib/buildpack-cve-tags"
require "#{buildpacks_ci_dir}/lib/buildpack-cve-notifier"
require "#{buildpacks_ci_dir}/lib/stack-cve-notifier"
require "#{buildpacks_ci_dir}/lib/cve-logger"

stacks_dir = File.expand_path(File.join(buildpacks_ci_dir, '..', 'stacks'))
cves_dir = File.expand_path(File.join(buildpacks_ci_dir, '..', 'new-cves'))
cve_logger = CVELogger.new(cves_dir)

StackCVENotifier.new(cve_logger, cves_dir, stacks_dir).run!('Ubuntu 14.04', 'ubuntu14.04')

languages = ['ruby']
languages.each do |language|
  rss_cves = BuildpackCVETags.new(language).related_cves
  BuildpackCVENotifier.run(language, rss_cves)
end
