#!/usr/bin/env ruby

buildpacks_ci_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))
new_releases_dir = File.expand_path(File.join(buildpacks_ci_dir, '..', 'new-releases'))

require "#{buildpacks_ci_dir}/lib/safe_execution"
require "#{buildpacks_ci_dir}/lib/slack-client"
require "#{buildpacks_ci_dir}/lib/tracker-client"

include SafeExecution

Dir.chdir("#{buildpacks_ci_dir}/scripts/notifications") do
  new_releases_output = `./new-releases #{new_releases_dir}`

  unless new_releases_output.nil? or new_releases_output.empty?

    slack_client = SlackClient.new(
      ENV['SLACK_WEBHOOK'],
      ENV['SLACK_CHANNEL'],
      'dependency-notifier'
    )
    slack_client.post_to_slack new_releases_output

    tracker_client = TrackerClient.new(
      ENV['TRACKER_API_TOKEN'],
      ENV['TRACKER_PROJECT_ID'],
      ENV['TRACKER_REQUESTER_ID'].to_i,
    )
    tracker_client.post_to_tracker "New releases", new_releases_output

  end
end

Dir.chdir(new_releases_dir) do
  execute_with_console_logging!("git add -A")
  execute_with_console_logging!("git commit -m 'Updates for latest tags'")
end
