#!/usr/bin/env ruby
# encoding: utf-8

buildpacks_ci_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))
require "#{buildpacks_ci_dir}/lib/tracker-client"
require 'json'

name = ARGV[0] || ''
description = ARGV[1] || ''

exit if name.empty?
description += "\n\n" unless description.empty?
description += "URL | Version\n"
description += "--- | ---\n"

Dir.glob('./*/input.json').each do |json_file|
  begin
    json = JSON.parse(File.read(json_file))
    description += "#{json['source']['url']} | #{json['version']['version'].strip.gsub(/\s+/, ' -- ')}\n"
  rescue
    description += "#{json_file} | ERROR\n"
  end
end
Dir.glob('./*/tag').each do |tag_file|
  begin
    tag = File.read(tag_file)
    version = File.read(tag_file.gsub(/tag$/,'version'))
    source = tag_file.gsub(/\/tag$/,'')
    description += "#{source} | #{tag} -- #{version}\n"
  rescue
    description += "#{tag_file} | ERROR\n"
  end
end

puts name
puts ""
puts description

tracker_client = TrackerClient.new(
  ENV['TRACKER_API_TOKEN'],
  ENV['TRACKER_PROJECT_ID'],
  ENV['TRACKER_REQUESTER_ID'].to_i
)
tracker_client.post_to_tracker name, description
