#!/usr/bin/env ruby
# encoding: utf-8

buildpacks_ci_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))
require "#{buildpacks_ci_dir}/lib/tracker-client"

name = ARGV[0]
description = ARGV[1]
tasks_array = ARGV[2..-1]

exit if description.empty?

tracker_client = TrackerClient.new(
  ENV['TRACKER_API_TOKEN'],
  ENV['TRACKER_PROJECT_ID'],
  ENV['TRACKER_REQUESTER_ID'].to_i
)
tracker_client.post_to_tracker(name: name, description: description, tasks: tasks_array, point_value: 1)
