#!/usr/bin/env ruby
# encoding: utf-8

require 'json'

name = ARGV[0]
description = ARGV[1]
exit if description.empty?

payload = {
  name: name,
  description: description,
  requested_by_id: 765_241
}.to_json

`
  curl -X POST \
       -vvvv \
       -H "X-TrackerToken: #{ENV['TRACKER_API_TOKEN']}" \
       -H "Content-Type: application/json" \
       -d '#{payload}' \
       "https://www.pivotaltracker.com/services/v5/projects/#{ENV['TRACKER_PROJECT_ID']}/stories"
`
