#!/usr/bin/env bash

gem install slackcat
DATE=$(date -d -2days +"%Y-%m-%d")
echo "@channel: The latests Ruby versions as of $DATE: $(git log --tags --pretty="format:%D" --after=$DATE | grep tag | cut -d " " -f 2)" | slackcat -c buildpacks-firehose -p
