#!/usr/bin/env bash

set -e

base_dir=$(pwd)

pushd buildpacks-ci/scripts/notifications
  bundle install
  new_releases_output=$(./new-releases $base_dir/new-releases)
  echo "$new_releases_output" | ./slack
  ./pivotal_tracker "New Releases" "$new_releases_output"
popd

pushd new-releases
  git add -A
  git commit -m 'Updates for latest tags' || true
popd
