#!/bin/bash -l

set -e

cd deployments-buildpacks
bundle -j4
. ./bin/switch stack-ci-8

cd ../cf-release/src/github.com/cloudfoundry/cf-acceptance-tests
go get github.com/tools/godep
godep restore
# create integration_config.json and set CONFIG env var (see README)
cat > integration_config.json <<EOF
{
  "api": "api.10.244.0.34.xip.io",
  "admin_user": "admin",
  "admin_password": "admin",
  "apps_domain": "10.244.0.34.xip.io",
  "skip_ssl_validation": true
}
EOF
export CONFIG=$PWD/integration_config.json  
./bin/test --nodes=4
