#!/bin/bash

set -e

mkdir -p cf-release/blobs/rootfs
filename=`cat cf-release/config/blobs.yml | grep cflinuxfs2 | cut -d ':' -f 1`
mv stack-s3/*.tar.gz cf-release/blobs/$filename

pushd cf-release
    bundle
    bosh --parallel 10 sync blobs
    bosh create release --force --with-tarball --name cf --version 212.0.`date +"%s"`
popd

rsync -a cf-release/ cf-release-artifacts
