#!/bin/sh

mkdir -p cf-release/blobs/rootfs
mv stack-s3/*.tar.gz cf-release/blobs/rootfs/cflinuxfs2.tar.gz
cd cf-release
apt-get -y install libmysqlclient-dev
bundle
bosh create release --force --with-tarball --name cf --version `cat ../cf-version/number`
