#!/bin/sh

mkdir -p /var/log
mkdir -p /var/run

# set up cgroups
mkdir -p /sys/fs/cgroup
mountpoint -q /sys/fs/cgroup || \
  mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup

for d in `sed -e '1d;s/\([^\t]\)\t.*$/\1/' /proc/cgroups`; do
  mkdir -p /sys/fs/cgroup/$d
  mountpoint -q /sys/fs/cgroup/$d || \
    mount -n -t cgroup -o $d cgroup /sys/fs/cgroup/$d
done

# docker graph dir
mkdir -p /var/lib/docker
mount -t tmpfs -o size=30G none /var/lib/docker

docker -d >/dev/null 2>&1 &

sleep 1

until docker info >/dev/null 2>&1; do
  echo waiting for docker to come up...
  sleep 1
done

cd stacks
apt-get -y install make
make

versioned_stack_filename=cflinuxfs2-`cat ../version/number`.tar.gz
mv cflinuxfs2.tar.gz $versioned_stack_filename

versioned_receipt_filename=../cflinuxfs2_receipt-`cat ../version/number`
echo "Rootfs SHASUM: `shasum $versioned_stack_filename | awk '{print $1}'`" > $versioned_receipt_filename
echo "" >> $versioned_receipt_filename
cat cflinuxfs2/cflinuxfs2_dpkg_l.out >> $versioned_receipt_filename

TERM=xterm-color git --no-pager diff cflinuxfs2/cflinuxfs2_receipt $versioned_receipt_filename || true
