#!/bin/bash

set -eux

SUFFIX="${STACKS_SUFFIX-}"

buildpacks-ci/scripts/start-docker

pushd stacks
  cp ../stacks-artifacts/cflinuxfs2$SUFFIX-*.tar.gz cflinuxfs2.tar.gz

  bundle install --jobs=$(nproc)

  bundle exec rspec
popd
