#!/bin/bash

aws_cred() {
cat <<EOF > config/private.yml
---
blobstore:
  s3:
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
EOF
  chmod 644 config/blobs.yml
}

main() {
  set -e
  local dest="stacks-release/blobs/rootfs"
  local version
  version=$(cat version/number)
  mkdir -p $dest
  cp stacks-s3/cflinuxfs2-*.tar.gz $dest

  pushd stacks-release
  aws_cred

  bosh -n upload blobs

  git add -A
  git commit -m "Bump stacks-release to $version"
  popd
}

main "$@"
