#!/bin/sh

set -e

mkdir -p cf-release/blobs/rootfs
cp stack-s3/cflinuxfs2-*.tar.gz cf-release/blobs/rootfs/
file_name=$(ls cf-release/blobs/rootfs)
cp receipt-s3/cflinuxfs2_receipt-* cf-release/spec/fixtures/receipts/cflinuxfs2_receipt
cd cf-release
bundle -j4

cat <<EOF > config/private.yml
---
blobstore:
  s3:
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
EOF

cat <<EOF > packages/rootfs_cflinuxfs2/spec
---
name: rootfs_cflinuxfs2
files:
- rootfs/$file_name
EOF

bosh -n upload blobs
chmod 644 config/blobs.yml

rspec spec/stacks_spec.rb

git config --global user.email "cf-buildpacks-eng@pivotal.io"
git config --global user.name "CF Buildpacks Team CI Server"

version=`cat ../version/number`
git commit -m "Bump rootfs to $version" -- config/blobs.yml spec/fixtures/receipts
