#!/bin/sh

set -e

mkdir -p cf-release/blobs/rootfs
cp stack-s3/cflinuxfs2-*.tar.gz cf-release/blobs/rootfs/cflinuxfs2.tar.gz
cp receipt-s3/cflinuxfs2_receipt-* cf-release/spec/fixtures/receipts/cflinuxfs2_receipt
cd cf-release
bundle -j4

cat <<EOF > config/final.yml
---
final_name: cf
min_cli_version: 1.5.0.pre.1001
blobstore:
  provider: local
  options:
    blobstore_path: /tmp/blobs
EOF

bosh -n upload blobs

rspec spec/stacks_spec.rb

git config --global user.email "cf-buildpacks-eng@pivotal.io"
git config --global user.name "CF Buildpacks Team CI Server"

version=`cat ../version/number`
git commit -m "Bump rootfs to $version" -- config/blobs.yml spec/fixtures/receipts
