---
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs5-rootfs-setup?/release
  value: cflinuxfs5
- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=cflinuxfs5-rootfs-setup?/properties/cflinuxfs5-rootfs/trusted_certs
  value:
    - ((diego_instance_identity_ca.ca))
    - ((credhub_tls.ca))
    - ((uaa_ssl.ca))
