#!/bin/bash -l
set -e

DEPLOYMENT_NAME=`cat cf-environments/name`

cd brats
bundle install
if [ -n "$CI_CF_PASSWORD" ]; then
  cf login -a api.$DEPLOYMENT_NAME.cf-app.com -u $CI_CF_USERNAME -p $CI_CF_PASSWORD -o pivotal -s integration --skip-ssl-validation
fi

if [ "$STACK" == "" ]; then
  bundle exec rspec cf_spec/integration/${LANGUAGE}_spec.rb
else
  bundle exec rspec -t stack:$STACK cf_spec/integration/${LANGUAGE}_spec.rb
fi
