#!/usr/bin/env ruby
require 'tempfile'
require_relative '../lib/commit'

old_version = File.open('VERSION', 'r') { |f| f.readline.chomp }

version_parts = old_version.match(/(\d+\.\d+\.)(\d+)/)
new_version = version_parts[1] + (version_parts[2].to_i + 1).to_s

File.write('VERSION', new_version)

new_changelog = Tempfile.new('CHANGELOG')
begin
  heading = "v#{new_version} #{Time.now.strftime('%b %d, %Y')}\n"
  new_changelog.write heading
  new_changelog.write '=' * heading.length
  new_changelog.write "\n\n"

  commits = begin
    Commit.recent(old_version)
  rescue StandardError
    nil
  end
  if commits
    commits.each do |commit|
      new_changelog.write commit.to_s
      new_changelog.write "\n\n"
    end
  else
    log = `git log v#{old_version}..HEAD`
    new_changelog.write log
  end

  new_changelog.write "\n"

  File.open('CHANGELOG', 'a+').each { |line| new_changelog.write line }
ensure
  new_changelog.close
end

`cp #{new_changelog.path} CHANGELOG`

puts "Bumped to #{`cat VERSION`}"
