#!/bin/bash -l

set -e

cd deployments-buildpacks
bundle -j4
. ./bin/switch $DEPLOYMENT_NAME

if [ -d ../cf-release/src/acceptance-tests ]; then
  cd ../cf-release/src/acceptance-tests
  mkdir -p /go/src/github.com/cloudfoundry/cf-acceptance-tests
  ln -s `pwd` /go/src/github.com/cloudfoundry/cf-acceptance-tests
else
  cd ../cf-release/src/github.com/cloudfoundry/cf-acceptance-tests
fi

go get github.com/tools/godep
godep restore
# create integration_config.json and set CONFIG env var (see README)
cat > integration_config.json <<EOF
{
  "api": "api.$DEPLOYMENT_NAME.cf-app.com",
  "admin_user": "$CI_CF_USERNAME",
  "admin_password": "$CI_CF_PASSWORD",
  "apps_domain": "$DEPLOYMENT_NAME.cf-app.com",
  "skip_ssl_validation": true
}
EOF
export CONFIG=$PWD/integration_config.json

if [ -f ./bin/test_default ]; then
  ./bin/test_default --nodes=4
else
  ./bin/test --nodes=4
fi
