#!/bin/bash -l

set -e

pushd deployments-buildpacks
  bundle -j4
  . ./bin/target_bosh $DEPLOYMENT_NAME
popd

if [ "$DIEGO_DOCKER_ON" = "true" ]
then
  cf api api.$DEPLOYMENT_NAME.cf-app.com --skip-ssl-validation
  echo -ne "\n" | cf login -u $CI_CF_USERNAME -p $CI_CF_PASSWORD
  cf enable-feature-flag diego_docker
fi

bosh run errand acceptance_tests

if [ "$DIEGO_DOCKER_ON" = "true" ]
then
  cf api api.$DEPLOYMENT_NAME.cf-app.com --skip-ssl-validation
  echo -ne "\n" | cf login -u $CI_CF_USERNAME -p $CI_CF_PASSWORD
  cf disable-feature-flag diego_docker
fi
