#!/usr/bin/env ruby
require 'yaml'

name = `hostname`.chomp

case ARGV[0]
  when 'edge'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/deployments-buildpacks.yml`)
    system('cf', 'api', 'api.edge.buildpacks-gcp.ci.cf-app.com', '--skip-ssl-validation') or raise 'Could not connect'
    system('cf', 'auth', 'admin', cfg['ci_cf_edge_password']) or raise 'Could not auth'
  when 'lts'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'api', cfg['ci-cf-lts-target'], '--skip-ssl-validation') or raise 'Could not connect'
    system('cf', 'auth', 'admin', cfg['ci-cf-lts-password']) or raise 'Could not auth'
  when 'bal'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'api', 'api.bal.buildpacks-gcp.ci.cf-app.com', '--skip-ssl-validation') or raise 'Could not connect'
    system('cf', 'auth', 'admin', cfg['ci-cf-bal-password']) or raise 'Could not auth'
  when 'cflinuxfs2'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'api', 'api.cflinuxfs2.buildpacks-gcp.ci.cf-app.com', '--skip-ssl-validation') or raise 'Could not connect'
    p('cf', 'auth', cfg['cflinuxfs2-cf-username'], cfg['cflinuxfs2-cf-password'])
    system('cf', 'auth', cfg['cflinuxfs2-cf-username'], cfg['cflinuxfs2-cf-password']) or raise 'Could not auth'
  when 'cf-release'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'api', 'api.cf-release.buildpacks-gcp.ci.cf-app.com', '--skip-ssl-validation') or raise 'Could not connect'
    p('cf', 'auth', cfg['cf-release-cf-username'], cfg['cf-release-cf-password'])
    system('cf', 'auth', cfg['cf-release-cf-username'], cfg['cf-release-cf-password']) or raise 'Could not auth'
  when 'dev'
    system('cf', 'api', 'api.v3.pcfdev.io', '--skip-ssl-validation') or raise 'Could not connect'
    system('cf', 'auth', 'admin', 'admin') or raise 'Could not connect'
  when 'pws'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'login', '-a', 'api.run.pivotal.io', '-u', cfg['pws-username'], '-p', cfg['pws-password'], '-o', 'cf-buildpacks', '-s', 'development') or raise 'Could not connect'
  else
    puts "Usage: #{$0} <edge|lts|bal|dev|pws>"
    exit 1
end

if ARGV[0] != 'pws'
  system('cf', 'create-org', name)
  system('cf', 'create-space', name, '-o', name)
  system('cf', 'target', '-o', name, '-s', name) or raise "Could not target #{name}"
end
