#!/usr/bin/env ruby
require 'yaml'

name = `hostname`.chomp

case ARGV[0]
  when 'edge'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/deployments-buildpacks.yml`)
    system('cf', 'api', 'api.edge.buildpacks-gcp.ci.cf-app.com', '--skip-ssl-validation') or raise 'Could not connect'
    system('cf', 'auth', 'admin', cfg['ci_cf_edge_password']) or raise 'Could not auth'
  when 'lts'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'api', cfg['ci-cf-lts-target'], '--skip-ssl-validation') or raise 'Could not connect'
    system('cf', 'auth', 'admin', cfg['ci-cf-lts-password']) or raise 'Could not auth'
  when 'bal'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'api', 'api.bal.buildpacks-gcp.ci.cf-app.com', '--skip-ssl-validation') or raise 'Could not connect'
    system('cf', 'auth', 'admin', cfg['ci-cf-bal-password']) or raise 'Could not auth'
  when 'cflinuxfs2'
    cfg = YAML.load(`lpass show --notes Shared-Buildpacks/concourse-private.yml`)
    system('cf', 'api', 'api.cflinuxfs2.buildpacks-gcp.ci.cf-app.com', '--skip-ssl-validation') or raise 'Could not connect'
    p('cf', 'auth', cfg['cflinuxfs2-cf-username'], cfg['cflinuxfs2-cf-password'])
    system('cf', 'auth', cfg['cflinuxfs2-cf-username'], cfg['cflinuxfs2-cf-password']) or raise 'Could not auth'
  when 'dev'
    system('cf', 'login', '-a', 'api.v3.pcfdev.io', '--skip-ssl-validation', '-u', 'admin', '-p', 'admin') or raise 'Could not connect'
  else
    puts "Usage: #{$0} <edge|lts|bal|dev>"
    exit 1
end

system('cf', 'create-org', name)
system('cf', 'create-space', name, '-o', name)
system('cf', 'target', '-o', name, '-s', name) or raise "Could not target #{name}"
