#!/bin/bash

set -e

cd resource-pools

cf_env=$1
resource=$2

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git mv "$cf_env/unclaimed/$resource" "$cf_env/claimed/$resource"

git add -A
git commit -m "Claiming Resource for bosh deployment $resource"
