#!/bin/bash -l

set -e

pushd deployments-buildpacks
  bundle -j4
  . ./bin/switch $DEPLOYMENT_NAME
  bosh deployment deployments/$DEPLOYMENT_NAME/diego-acceptance-tests.yml
popd

bosh run errand acceptance_tests
