#!/bin/bash -l

set -exu

pushd deployments-buildpacks
#replace ruby Gemfile with the available version
sed -i '$ s/line number//g' Gemfile
echo "ruby '$(ruby -v | awk '{split($0,a," ");split(a[2],b,"p"); print b[1]}')'" >> Gemfile
bundle install
. ./bin/switch "$DEPLOYMENT_NAME"
popd

# manifest-generation/misc-templates/aws-iaas-settings.yml 
pushd diego-release
./scripts/update
./scripts/print-director-stub > /tmp/director.yml

# generate-deployment-manifest is looking for cf.yml, so replace it with
# manifest.yml
sed -i -E "s/\/cf.yml/\/manifest.yml/g" ./scripts/generate-deployment-manifest

./scripts/generate-deployment-manifest \
  /tmp/director.yml \
  manifest-generation/bosh-lite-stubs/property-overrides.yml \
  manifest-generation/bosh-lite-stubs/instance-count-overrides.yml \
  manifest-generation/bosh-lite-stubs/persistent-disk-overrides.yml \
  manifest-generation/bosh-lite-stubs/iaas-settings.yml \
  manifest-generation/bosh-lite-stubs/additional-jobs.yml \
  ../deployments-buildpacks/deployments/$DEPLOYMENT_NAME \
  > diego-deployment.yml
bosh deployment diego-deployment.yml
bosh upload release https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release | true
bosh create release --force --name diego &&
  bosh -n upload release &&
  bosh -n deploy
popd

