#!/bin/bash -l

set -e

export CF_RELEASE_DIR=`pwd`/cf-release

pushd deployments-buildpacks
  bundle -j4
  source ./bin/switch $DEPLOYMENT_NAME
popd

cd cf-release 

echo "
---
name: cf-warden
properties:
  domain: $DEPLOYMENT_NAME.cf-app.com
  acceptance_tests:
    admin_password: $CF_CI_PASSWORD
    include_internet_dependent: true
    include_logging: true
    include_operator: false
    include_routing: false
    include_security_groups: true
    include_services: true
    include_sso: false
    include_v3: false
jobs:
- name: api_z1
  # Make the disk size bigger so we can handle
  # both offline and online buildpacks now.
  persistent_disk: 30720" >> bosh-lite/cf-stub-spiff-ours.yml

./scripts/generate-bosh-lite-dev-manifest bosh-lite/cf-stub-spiff-ours.yml

ruby -i -pe "gsub('admin|admin', 'admin|' + ENV['CF_CI_PASSWORD'])" bosh-lite/deployments/cf.yml

cd ../deployments-buildpacks
cp ../cf-release/bosh-lite/deployments/cf.yml deployments/$DEPLOYMENT_NAME/manifest.yml

git add deployments/$DEPLOYMENT_NAME/manifest.yml
git diff-index --quiet HEAD deployments/$DEPLOYMENT_NAME/manifest.yml || git commit -qm "Update manifest for $DEPLOYMENT_NAME"
