#!/bin/bash -l

set -e
DOMAIN_NAME=${DOMAIN_NAME:-cf-app.com}
ROOTFS_RELEASE="${ROOTFS_RELEASE:-cflinuxfs2-rootfs}"

pushd deployments-buildpacks
  bundle config mirror.https://rubygems.org ${RUBYGEM_MIRROR}
  bundle install --jobs=$(nproc)
  source ./bin/target_bosh $DEPLOYMENT_NAME
popd

export BOSH_RELEASES_DIR=`pwd`
export CF_RELEASE_DIR=`pwd`/cf-release

pushd cf-release
  mkdir -p bosh-lite
  echo "
---
name: cf-warden
properties:
  domain: $DEPLOYMENT_NAME.$DOMAIN_NAME
  system_domain: $DEPLOYMENT_NAME.$DOMAIN_NAME
  acceptance_tests:
    admin_password: stub_to_be_gsubbed
    include_internet_dependent: true
    include_logging: true
    include_operator: false
    include_routing: false
    include_security_groups: true
    include_services: true
    include_sso: false
    include_v3: false
    include_diego_ssh: true
    include_diego_docker: true
    nodes: 4
    backend: diego
  cc:
    default_to_diego_backend: true

jobs:
- name: api_z1
  # Make the disk size bigger so we can handle
  # both offline and online buildpacks now.
  persistent_disk: 30720" >> bosh-lite/cf-stub-spiff-ours.yml

  ./scripts/generate-bosh-lite-dev-manifest bosh-lite/cf-stub-spiff-ours.yml

  ../buildpacks-ci/scripts/swap-cf-release-scim-admin-password.rb $(pwd) bosh-lite/deployments/cf.yml

  ruby -i -pe "gsub('admin_password: stub_to_be_gsubbed', 'admin_password: ' + ENV['CI_CF_PASSWORD'])" bosh-lite/deployments/cf.yml
popd

pushd diego-release
  ./scripts/generate-bosh-lite-manifests
  ../buildpacks-ci/scripts/swap-diego-rootfs-release.rb $(pwd) bosh-lite/deployments/diego.yml
popd

pushd deployments-buildpacks
  cp ../cf-release/bosh-lite/deployments/cf.yml deployments/$DEPLOYMENT_NAME/manifest.yml
  cp ../diego-release/bosh-lite/deployments/diego.yml deployments/$DEPLOYMENT_NAME/diego.yml

  git add deployments/$DEPLOYMENT_NAME/*.yml
  git diff-index --quiet HEAD deployments/$DEPLOYMENT_NAME/manifest.yml || git commit -qm "Update manifests for $DEPLOYMENT_NAME"
popd

rsync -a deployments-buildpacks/ generate-manifest-artifacts
