#!/bin/bash -l

set -e

function acceptance_test_backend {
    case $DEPLOYMENT_NAME in
        edge-2.buildpacks.ci)           echo -n "diego";;
        edge-4.buildpacks.ci)           echo -n "diego";;
        diego-stacks.buildpacks.ci)     echo -n "diego";;
        diego-cf-release.buildpacks.ci) echo -n "diego";;
        *)                              echo -n "dea";;
    esac
}

function use_diego_backend {
    if [[ `acceptance_test_backend` == "diego" ]]; then
        echo -n true
    else
        echo -n false
    fi
}

pushd deployments-buildpacks
  bundle -j4
  source ./bin/switch $DEPLOYMENT_NAME
popd

export BOSH_RELEASES_DIR=`pwd`
export CF_RELEASE_DIR=`pwd`/cf-release

pushd cf-release
  mkdir -p bosh-lite
  echo "
---
name: cf-warden
properties:
  domain: $DEPLOYMENT_NAME.cf-app.com
  acceptance_tests:
    admin_password: $CI_CF_PASSWORD
    include_internet_dependent: true
    include_logging: true
    include_operator: false
    include_routing: false
    include_security_groups: true
    include_services: true
    include_sso: false
    include_v3: false
    include_diego_ssh: $(use_diego_backend)
    include_diego_docker: $(use_diego_backend)
    nodes: 4
    backend: $(acceptance_test_backend)
  cc:
    default_to_diego_backend: $(use_diego_backend)

jobs:
- name: api_z1
  # Make the disk size bigger so we can handle
  # both offline and online buildpacks now.
  persistent_disk: 30720" >> bosh-lite/cf-stub-spiff-ours.yml

  ./scripts/generate-bosh-lite-dev-manifest bosh-lite/cf-stub-spiff-ours.yml

  ruby -i -pe "gsub('admin|admin', 'admin|' + ENV['CI_CF_PASSWORD'])" bosh-lite/deployments/cf.yml
popd

pushd diego-release
  if [ "x${USE_STACK_RELEASE}" == "xyes" ]; then
      ./scripts/generate-bosh-lite-manifests -r
  else
      ./scripts/generate-bosh-lite-manifests
  fi
popd

pushd deployments-buildpacks
  cp ../cf-release/bosh-lite/deployments/cf.yml deployments/$DEPLOYMENT_NAME/manifest.yml
  cp ../diego-release/bosh-lite/deployments/diego.yml deployments/$DEPLOYMENT_NAME/diego.yml

  git add deployments/$DEPLOYMENT_NAME/*.yml
  git diff-index --quiet HEAD deployments/$DEPLOYMENT_NAME/manifest.yml || git commit -qm "Update manifests for $DEPLOYMENT_NAME"
popd

rsync -a deployments-buildpacks/ generate-manifest-artifacts
