#!/bin/bash -l

set -e

pushd deployments-buildpacks
  bundle -j4
  source ./bin/switch $DEPLOYMENT_NAME
popd

export BOSH_RELEASES_DIR=`pwd`
export CF_RELEASE_DIR=`pwd`/cf-release

pushd cf-release
  echo "
---
name: cf-warden
properties:
  domain: $DEPLOYMENT_NAME.cf-app.com
  acceptance_tests:
    admin_password: $CI_CF_PASSWORD
    include_internet_dependent: true
    include_logging: true
    include_operator: false
    include_routing: false
    include_security_groups: true
    include_services: true
    include_sso: false
    include_v3: false
  cc:
    default_to_diego_backend: false

jobs:
- name: api_z1
  # Make the disk size bigger so we can handle
  # both offline and online buildpacks now.
  persistent_disk: 30720" >> bosh-lite/cf-stub-spiff-ours.yml

  ./scripts/generate-bosh-lite-dev-manifest bosh-lite/cf-stub-spiff-ours.yml

  ruby -i -pe "gsub('admin|admin', 'admin|' + ENV['CI_CF_PASSWORD'])" bosh-lite/deployments/cf.yml
popd

pushd deployments-buildpacks
  cp ../cf-release/bosh-lite/deployments/cf.yml deployments/$DEPLOYMENT_NAME/manifest.yml

  git add deployments/$DEPLOYMENT_NAME/manifest.yml
  git diff-index --quiet HEAD deployments/$DEPLOYMENT_NAME/manifest.yml || git commit -qm "Update manifest for $DEPLOYMENT_NAME"
popd

rsync -a deployments-buildpacks/ deployments-buildpacks-artifacts
