#!/bin/bash -l

set -e

export CF_RELEASE_DIR=`pwd`/cf-release

pushd deployments-buildpacks
  bundle -j4
  source ./bin/switch $DEPLOYMENT_NAME
popd

cd bosh-lite

echo "
---
name: cf-warden
director_uuid: PLACEHOLDER-DIRECTOR-UUID
releases:
  - name: cf
    version: latest
properties:
  domain: $DEPLOYMENT_NAME.cf-app.com
  loggregator_endpoint:
    shared_secret: PLACEHOLDER-LOGGREGATOR-SECRET
jobs:
- name: api_z1
  # Make the disk size bigger so we can handle
  # both offline and online buildpacks now.
  persistent_disk: 30720" > manifests/cf-stub-spiff.yml

./bin/make_manifest_spiff

cd ../deployments-buildpacks
cp ../bosh-lite/manifests/cf-manifest.yml deployments/$DEPLOYMENT_NAME/manifest.yml

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git add deployments/$DEPLOYMENT_NAME/manifest.yml
git diff-index --quiet HEAD deployments/$DEPLOYMENT_NAME/manifest.yml || git commit -qm "Update manifest for $DEPLOYMENT_NAME"
