#!/bin/bash -l

set -eux

rsync -a deployments-buildpacks/ deployments-buildpacks-artifacts

cd deployments-buildpacks-artifacts
bundle install -j4
. ./bin/switch $DEPLOYMENT_NAME --no-target

cd deployments/$DEPLOYMENT_NAME
rm -f .vagrant/machines/default/aws/elastic_ip
vagrant destroy -f
vagrant up --provider=aws

git add -A
git commit -m "recreated deployment $DEPLOYMENT_NAME"

until $(curl -k --output /dev/null --silent --head --fail https://$DEPLOYMENT_NAME.cf-app.com:25555/info); do
    printf '.'
    sleep 10
done

bosh -u admin -p admin -t $DEPLOYMENT_NAME.cf-app.com create user admin $PASSWORD

if [ -e *.yml ]; then
  rm -f *.yml
  git add -A
  git commit -m "remove deployment manifests for $DEPLOYMENT_NAME"
fi
