#!/bin/bash -l

set -eux
IAAS=${IAAS:-aws}
SCRIPT_DIR=$(pwd)/$(dirname $0)

rsync -a deployments-buildpacks/ deployments-buildpacks-artifacts

cd deployments-buildpacks-artifacts
bundle config mirror.https://rubygems.org ${RUBYGEM_MIRROR}
bundle install -j4 --retry 5
. bin/target_bosh --no-target
export BOSH_LITE_PRIVATE_KEY=$(pwd)/keys/bosh.pem

cd deployments/$DEPLOYMENT_NAME
if [ "$IAAS" = "aws" ]; then
  $SCRIPT_DIR/terminate-bosh-lite
  rm -rf .vagrant

  export VAGRANT_CWD=$(pwd)
  vagrant up --provider=aws
elif [ "$IAAS" = "azure" ]; then
  # Set up BOSH user and password for Azure BOSH, currently bosh-lite user and password
  BOSH_USER_TO_RESTORE=$BOSH_USER
  BOSH_PASSWORD_TO_RESTORE=$BOSH_PASSWORD
  export BOSH_USER=$AZURE_BOSH_USER
  export BOSH_PASSWORD=$AZURE_BOSH_PASSWORD

  # Clean up and destroy old bosh-lite VM
  BOSH_TARGET=bosh.buildpacks-azure.ci.cf-app.com ../../bin/target_bosh concourse-azure
  echo "yes" | bosh delete deployment $AZURE_BOSH_LITE_NAME

  # Boot up new bosh-lite VM
  # Use correct director uuid in bosh-lite manifest
  cp bosh-lite/bosh-lite-template.yml bosh-lite.yml
  sed -i "s|^director_uuid:.*$|director_uuid: $(bosh status --uuid)|" bosh-lite.yml

  bosh deployment bosh-lite.yml
  echo "yes" | bosh deploy

  export BOSH_USER=$BOSH_USER_TO_RESTORE
  export BOSH_PASSWORD=$BOSH_PASSWORD_TO_RESTORE
else
  echo "Please specify IAAS=(aws|azure)"
  exit 1
fi

git add -A
git commit -m "recreated deployment $DEPLOYMENT_NAME"

until $(curl -k --output /dev/null --silent --head --fail https://$DEPLOYMENT_NAME.cf-app.com:25555/info); do
    printf '.'
    sleep 10
done

# Destroy deployment if we are not able to connect and update the user
if bosh -u admin -p admin -t $DEPLOYMENT_NAME.cf-app.com create user admin $PASSWORD; then
  echo "Deployment working!"
else
  if [ "$IAAS" = "aws" ]; then
    echo "Deployment failed deleting instance"
    $SCRIPT_DIR/terminate-bosh-lite
    rm -rf .vagrant
    exit 1
  fi
fi

if test -n "$(find . -maxdepth 1 -name '*.yml' -print -quit)"; then
  rm -f *.yml
  git add -A
  git commit -m "remove deployment manifests for $DEPLOYMENT_NAME"
fi
