#!/bin/bash -l

set -ex

pushd deployments-buildpacks
  bundle config mirror.https://rubygems.org ${RUBYGEM_MIRROR}
  bundle install
  . ./bin/target_bosh $DEPLOYMENT_NAME
popd

bosh -d deployments-buildpacks/deployments/stacks.buildpacks.ci/rootfs-smoke-test.yml run errand cflinuxfs2-smoke-test
