#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

set -x

export IMAGE_ROOT="$PWD/image-root"

mkdir -p /sys/fs/cgroup
mountpoint -q /sys/fs/cgroup || \
  mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup

sed -e '1d;s/\([^\t]\)\t.*$/\1/' < /proc/cgroups | while IFS= read -r d; do
  mkdir -p "/sys/fs/cgroup/$d"
  "mountpoint -q /sys/fs/cgroup/$d" || \
    mount -n -t cgroup -o "$d" cgroup "/sys/fs/cgroup/$d"
done

mkdir /tmp/build/graph
mount -t tmpfs -o size=42g tmpfs /tmp/build/graph
dockerd -g /tmp/build/graph -s aufs --mtu 1432 &

until docker info >/dev/null 2>&1; do
  echo waiting for docker to come up...
  sleep 1
done
