#!/bin/sh
mkdir -p ~/.aws
echo "[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
echo "[default]\nregion = us-east-1\n" > ~/.aws/config

## Note, do NOT turn on the 'x' flag, or the above, or private data will
## be printed in concourse
set -ex

aws ec2 describe-instances --query 'Reservations[*].Instances[*].{id:InstanceId,tags:Tags[0].Value,state:State.Name}' --output text | grep running | grep $BOSH_LITE_NAME | cut -f 1 | xargs -I {} aws ec2 terminate-instances --instance-ids {}

while [ -n "$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].{id:InstanceId,tags:Tags[0].Value,state:State.Name}' --output text | grep -v terminated | grep $BOSH_LITE_NAME)" ]
do
  echo 'waiting'
  sleep 10
done
