#!/bin/bash -l
set -e

DEPLOYMENT_NAME=`cat cf-environments/name`

pushd deployments-buildpacks
  bundle -j4
  source ./bin/switch $DEPLOYMENT_NAME
popd

cd buildpack

for stack in $STACKS; do
  ../ci-tools/buildpack-build --uncached --stack=$stack --host=$DEPLOYMENT_NAME.cf-app.com
  ../ci-tools/buildpack-build --cached --stack=$stack --host=$DEPLOYMENT_NAME.cf-app.com
done
