#!/usr/bin/env bash

set -e

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

cd buildpack/compile-extensions
git checkout master
git pull origin master
bundle install
bundle exec rspec
cd ..

git add compile-extensions/
git commit -m "Update compile-extensions"
