#!/usr/bin/env bash

set -ex

BUILDPACK_PACKAGER_VERSION=$(cat buildpack-packager/version)
NEW_VERSION_LINE="gem 'buildpack-packager', git: 'https://github.com/cloudfoundry/buildpack-packager', tag: 'v$BUILDPACK_PACKAGER_VERSION'"

pushd buildpack
  sed -i "s|^gem 'buildpack-packager'.*$|$NEW_VERSION_LINE|" cf.Gemfile
  BUNDLE_GEMFILE=cf.Gemfile bundle install
  git add cf.Gemfile cf.Gemfile.lock
  git commit -m "Update buildpack-packager to $BUILDPACK_PACKAGER_VERSION"
popd

rsync -a buildpack/ buildpack-artifacts
