#!/usr/bin/env bash

set -ex

BUILDPACK_PACKAGER_VERSION=$(cat buildpack-packager/version)
NEW_VERSION_LINE="gem 'buildpack-packager', git: 'https://github.com/cloudfoundry/buildpack-packager', tag: 'v$BUILDPACK_PACKAGER_VERSION'"

pushd buildpack
  sed -i "s|^gem 'buildpack-packager'.*$|$NEW_VERSION_LINE|" cf.Gemfile
  bundle config mirror.https://rubygems.org ${RUBYGEM_MIRROR}
  BUNDLE_GEMFILE=cf.Gemfile bundle install
  git add cf.Gemfile cf.Gemfile.lock

  set +e
    diff=$(git diff --cached --exit-code)
    no_changes=$?
  set -e

  if [ $no_changes -ne 0 ]
  then
    git commit -m "Update buildpack-packager to $BUILDPACK_PACKAGER_VERSION"
  else
    echo "buildpack-packager in buildpack is up to date"
  fi
popd

rsync -a buildpack/ buildpack-artifacts
