#!/usr/bin/env bash

set -ex

pushd buildpack/compile-extensions
  git checkout master
  git pull origin master
  bundle config mirror.https://rubygems.org ${RUBYGEM_MIRROR}
  bundle install
  bundle exec rspec
popd

pushd buildpack
  git add compile-extensions/
  git commit -m "Update compile-extensions"
popd

rsync -a buildpack/ buildpack-artifacts
