#!/usr/bin/env ruby
# encoding: utf-8

require_relative 'concourse2tracker'
require 'json'

source_dir = ARGV.shift

payload = JSON.parse(ARGF.read)
params  = payload['params']

Dir.chdir(source_dir) do
  Concourse2Tracker.new(
    git_path: params['git_path'],
    project_id: params['project_id'],
    api_token: params['api_token']
  ).process!
end

puts({
  version: { ref: Time.now },
  metadata: []
}.to_json)
