#!/usr/bin/env ruby

require_relative 'concourse2tracker'
require 'json'

_ = ARGV.shift

payload = JSON.parse(ARGF.read)
params  = payload['params']

Concourse2Tracker.new(
  git_path: params['git_path'],
  project_id: params['project_id'],
  api_token: params['api_token']
).process!
