#!/usr/bin/env bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging
set -eu +x -o pipefail

payload=$TMPDIR/cf-space-resource-request
cat > $payload <&0

DESTINATION=$1
TARGET=`jq -r '.source.target' < $payload`
USERNAME=`jq -r '.source.username' < $payload`
PASSWORD=`jq -r '.source.password' < $payload`
ORGANIZATION=`jq -r '.source.organization' < $payload`
SPACE=`jq -r '.version.ref' < $payload`

echo "#!/usr/bin/env sh" > $DESTINATION/login
echo "set +x" >> $DESTINATION/login
echo "echo Logging in to $SPACE on $ORGANIZATION on $TARGET" >> $DESTINATION/login
echo "cf login -a $TARGET -u $USERNAME -p $PASSWORD --skip-ssl-validation -o $ORGANIZATION -s $SPACE" >> $DESTINATION/login
chmod 755 $DESTINATION/login
source $DESTINATION/login

echo $SPACE > $DESTINATION/name
echo "export SPACE=$SPACE" > $DESTINATION/variables

echo "{\"version\": {\"ref\": \"$SPACE\"}}" >&3
