#!/usr/bin/env bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging
set -eu +x -o pipefail

payload=$TMPDIR/cf-space-resource-request
cat > "$payload" <&0

TARGET=$(jq -r '.source.target' < "$payload")
USERNAME=$(jq -r '.source.username' < "$payload")
PASSWORD=$(jq -r '.source.password' < "$payload")
ORGANIZATION=$(jq -r '.source.organization' < "$payload")

cf api "$TARGET" --skip-ssl-validation
cf auth "$USERNAME" "$PASSWORD"

SPACE=$(openssl rand -base64 32 | base64 | head -c 8 | awk '{print tolower($0)}')
cf create-space "$SPACE" -o "$ORGANIZATION"

echo "{\"version\": {\"ref\":\"$SPACE\"},\"metadata\":[]}" >&3
