#@data/values
---
language: nginx
organization: cloudfoundry

buildpack:
  stacks:
  - cflinuxfs4
  # - cflinuxfs5  # TODO: re-enable when cf-runtime cflinuxfs5 support is ready
  product_slug: nginx-buildpack
  skip_docker_start: true
  skip_brats: true
  compute_instance_count: 1
