# encoding: utf-8
source 'https://rubygems.org'

ruby '2.3.1'

gem 'machete', git: 'https://github.com/cf-buildpacks/machete', tag: 'v0.0.18'
gem 'buildpack-packager', git: 'https://github.com/cloudfoundry/buildpack-packager'
gem 'rspec'
gem 'rspec-instafail'
gem 'pry'
gem 'bcrypt'
