#!/usr/bin/env ruby
# encoding: utf-8
require 'fileutils'

artifact_path = File.join(Dir.pwd, 'machete-artifacts')

current_version = Dir.chdir('machete') do
  current_version = `bump current | egrep -o '[0-9\.]+'`
  tag = "v#{current_version}"
  File.write(File.join(artifact_path, 'tag'), tag)
  current_version.strip
end

compressed_file_target = "#{artifact_path}/machete-v#{current_version}"
`zip -r #{compressed_file_target}.zip machete`
`tar -cvzf #{compressed_file_target}.tar.gz machete`
